version: "3.8"

services:
  app:
    restart: always
    environment:
      - PORT=8000
      - NIKTO_VERSION=2.5.0
    build:
      context: .
      target: builder
    command: npm run dev
    ports:
      - 8000:8000
    volumes:
      - .:/app
